# Generated by Django 3.1.12 on 2022-07-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ein', models.TextField()),
                ('businessStructure', models.JSONField()),
                ('address', models.JSONField()),
                ('cellphone', models.TextField()),
                ('creationDate', models.DateTimeField(verbose_name='date published')),
                ('active', models.BooleanField()),
            ],
        ),
    ]
