# Generated by Django 3.1.12 on 2022-07-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='businessStructure',
            field=models.JSONField(default=dict),
        ),
    ]
