# Generated by Django 4.0.6 on 2022-07-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220723_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.JSONField(default=dict)),
                ('productAmount', models.IntegerField()),
                ('total', models.FloatField()),
                ('issueDate', models.TextField()),
                ('base64', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='creationDate',
            field=models.DateTimeField(),
        ),
    ]
