# Generated by Django 4.0.6 on 2022-07-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_order_alter_company_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.company'),
        ),
    ]
