# Generated by Django 4.0.6 on 2022-07-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_order_costumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='businessStructure',
        ),
        migrations.RemoveField(
            model_name='order',
            name='costumer',
        ),
    ]
