# Generated by Django 4.0.6 on 2022-07-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_company_businessstructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='structure',
            field=models.CharField(choices=[('LLC', 'LIMITED LIABILITY COMPANY'), ('SP', 'SOLE PROPRIETORSHIPS'), ('PARTNER', 'PARTNERSHIP'), ('CORP', 'CORPORATION'), ('S CORP', 'S CORPORATION'), ('ND', 'NOT DEFINED')], default='ND', max_length=7),
        ),
    ]
